name: Veracode Upload & Scan
on: workflow_dispatch
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    env:
        VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Download CLI
        uses: wei/curl@master
        with:
          args: -fsS https://tools.veracode.com/veracode-cli/install | sh
          
      - name: Package Application
        run: ./veracode package -s . -o veracode-artifact -a trust
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'Go-Demo'
          createprofile: false
          filepath: 'veracode-artifact'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          createsandbox: 'false'
#          sandboxname: 'GitHub Actions'
#          scantimeout: 0
#          exclude: '*.js'
#          criticality: 'VeryHigh'
